// Main pages barrel export
export { default as About } from "./About"
export { default as AllLoans } from "./AllLoans"
export { default as ApplyLoan } from "./ApplyLoan"
export { default as Contact } from "./Contact"
export { default as ForgotPassword } from "./ForgotPassword"
export { default as Home } from "./Home"
export { default as LoanDetails } from "./LoanDetails"
export { default as Login } from "./Login"
export { default as NotFound } from "./NotFound"
export { default as PaymentCancel } from "./PaymentCancel"
export { default as PaymentSuccess } from "./PaymentSuccess"
export { default as Receipt } from "./Receipt"
export { default as Register } from "./Register"
